# Meta Data for SEO

## Homepage
title = "雪云网络"
titleSeparator = "-"
titleAddition = "软件定义网络解决方案提供商"
description = "提供开源的混合云、分支机构互联、IDC互通、远程办公、云专线等解决方案，自研商业化产品可满足SLA、安全等需求。用最低的成本解决最核心的网络需求。"

## Open Graph
ogLocale = "zh_CN"
# 似乎没有用到
domainTLD = "xuecloud.co"
titleHome = "雪云网络"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# 备案信息
footer = "Copyright (c) 2022 广州市雪云网络科技有限责任公司<br><a href=\"https://beian.miit.gov.cn/\" target=\"_blank\" rel=\"noopener noreferrer\">粤ICP备2022009793号</a>"

# Feed
copyRight = "Copyright (c) 2022 广州市雪云网络科技有限责任公司"

# Alert
# 顶栏消息框开关
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\">Check out Doks v0.2</a>"

# Edit Page
# 编辑页面开关
editPage = false
repoHost = "GitHub"
docsRepo = "https://github.com/xueCloud"
docsRepoBranch = "main"

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = false
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  collapsibleSidebar = true
  multilingualMode = false
  docsVersioning = false
